[phases.setup]
nixPkgs = ["nodejs_20", "pnpm", "ffmpeg", "noto-fonts-cjk-sans"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm exec prisma generate"]

[start]
cmd = "pnpm worker"
